POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "username": "Darren",
    "name": "Darren Fisher",
    "password": "secret",
    "location": "South Akl",
    "quote": "Been binging tv shows, lets have a eat"
}

